# Generated by Django 5.2.13 on 2026-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(default="shop/default.webp", upload_to="shop/"),
                ),
                ("price", models.IntegerField(default=None)),
                ("disscount", models.IntegerField(default=None)),
                ("score", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=None)),
                ("category", models.ManyToManyField(to="shop.category")),
            ],
        ),
    ]
